name: Build Dev Container
on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Installation mode'
        required: true
        default: 'complete'
        type: choice
        options:
          - bare
          - vscode
          - nvim
          - complete
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Get latest commit hash from main branch
      id: get_commit_hash
      run: |
        COMMIT_HASH=$(git rev-parse origin/main)
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
    - name: Set up Docker BuildKit
      run: |
        export DOCKER_BUILDKIT=1
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set build arguments
      id: build_args
      run: |
        case "${{ github.event.inputs.mode }}" in
          "bare")
            echo "INSTALL_VSCODE=false" >> $GITHUB_ENV
            echo "INSTALL_NVIM=false" >> $GITHUB_ENV
            ;;
          "vscode")
            echo "INSTALL_VSCODE=true" >> $GITHUB_ENV
            echo "INSTALL_NVIM=false" >> $GITHUB_ENV
            ;;
          "nvim")
            echo "INSTALL_VSCODE=false" >> $GITHUB_ENV
            echo "INSTALL_NVIM=true" >> $GITHUB_ENV
            ;;
          "complete")
            echo "INSTALL_VSCODE=true" >> $GITHUB_ENV
            echo "INSTALL_NVIM=true" >> $GITHUB_ENV
            ;;
        esac
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/dev-container:${{ env.COMMIT_HASH }}-${{ github.event.inputs.mode }}
          ${{ secrets.DOCKER_USERNAME }}/dev-container:${{ github.event.inputs.mode }}
        build-args: |
          INSTALL_VSCODE=${{ env.INSTALL_VSCODE }}
          INSTALL_NVIM=${{ env.INSTALL_NVIM }}
        secrets: |
          "chezmoi_read_token=${{ secrets.CHEZMOI_READ_TOKEN }}"
        context: .
        file: Dockerfile
        platforms: linux/amd64