name: Build Dev Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get latest commit hash from main branch
      id: get_commit_hash
      run: |
        COMMIT_HASH=$(git rev-parse origin/main)
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

    - name: Set up Docker BuildKit
      run: |
        export DOCKER_BUILDKIT=1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/dev-container:${{ env.COMMIT_HASH }}
        context: .
        file: Dockerfile
        platforms: linux/amd64
